from getpass import getpass
import os
import time

def menu():
      while True:
           print("")
           os.system("clear")
           print('\033[1;36;40m──▄▀▀▀▄───────────────\nPlease Login To Continue\n─███████─────────▄▀▀▄─\n░██─▀─██░░█▀█▀▀▀▀█░░█░\n░███▄███░░▀░▀░░░░░▀▀░░ ' )
           print('')
           print( '\033[1;37mAuthor : Angga Rismayana\n\033[1;37mTeam   : CYBER MUSLIM\nIG     : rismayanaangga_04\n\n[ Hackers \033[1;37mINDO\033[1;31mNESIA\033[1;37m ]' )
           print("")
           try:
                x = str(input(' \033[1;37mUsername\033[1;32m : '))
                print("")
                e = getpass(' \033[1;37mPassword\033[1;32m : ')
                print ("")
                if x=="Angga rismayana" and e=="Angga321":
                   print('\033[1;37mPlease wait ..')
                   time.sleep(5)
                   print('\033[1;32mLogin Success [✓]')
                   time.sleep(3)
                   print('')
                   time.sleep(0.1)
                   print( ' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Welcome to my termux hacking  profesional')
                   time.sleep(0.1)
                   print(' Welcome to my termux hacking profesional')
                   time.sleep(0.1)
                   print(' Welcome to my termux hacking profesional')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Termux is opening network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Welcome to my termux Hacking Prodsional')
                   time.sleep(0.1)
                   print(' Welcome to my termux Hacking Prodsional')
                   time.sleep(0.1)
                   print(' Welcome to my termux Hacking Prodsional')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Termux is opening network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Welcome to my termux Hacking Prodsional')
                   time.sleep(0.1)
                   print(' Welcome to my termux Hacking Prodsional')
                   time.sleep(0.1)
                   print(' Welcome to my termux Hacking Prodsional')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Termux is opening network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(3)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Welcome to my termux Hacking Prodsional')
                   time.sleep(0.1)
                   print(' Welcome to my termux ')
                   time.sleep(0.1)
                   print(' Welcome to my termux Hacking Prodsional')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Termux is opening network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' System Login to network ')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Welcome to my termux Internasional')
                   time.sleep(0.1)
                   print(' Welcome to my termux Internasional')
                   time.sleep(0.1)
                   print(' Welcome to my termux Internasional')
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' Enter the international network' )
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' System Termux Terinstall')
                   time.sleep(0.1)
                   print(' Open Termux')
                   time.sleep(2)

                   os.system('clear')

                   print('')
                   print('\033[1;37m ╔════════════════════════════════╗\n         \033[1;35mWELCOME MY TERMUX\n           \033[1;37m[ \033[1;31mINDO\033[1;37mNESIA ]\n\n  Author : Angga Rismayana\n  Team   : CYBER MUSLIM\n  IG     : rismayanaangga_04\n\n ╚════════════════════════════════╝')
                   time.sleep(1)
                   print(' ')
                   time.sleep(4)
                   print('\033[1;32m ')
                   print("")
                   break
                else:
                      print("")
                      print("\033[1;91m Salah Goblok !")
                      time.sleep(2)
                      print("")
           except Exception:
                      print("\033[1;91m Ada yg salah kont*l !\n Coba Cek lagi !")
                      time.sleep(4)
           except KeyboardInterrupt:
                      print("")
                      os.system('killall -9 com.termux')
                      print("")
                      print("\033[1;91m Salah Goblok")
                      time.sleep(2)

menu ()
